### PR TITLE
Add support for new devices, and fix j7ltechn

### PR DESCRIPTION
**Pull request by zqm64**
Device List:
J3109 - j3ltectc
J3110 - j3xproltechn
J3119 - j3xproltectc
J5108 - j5xltecmcc
J7008 - j7ltechn

I will upload device trees lately

### CODE REVIEW

**Comment by zqm64** [comment]
kernel is OK, without breaking other devices

**Comment by zakaryan2004** [comment]
Pull requests aren't supported, push to Gerrit(review.msm8916.com) instead.

**Comment by zqm64** [comment]
> Pull requests aren't supported, push to Gerrit(review.msm8916.com) instead.

Okay. But what about new device trees?

**Comment by zakaryan2004** [comment]
The PR still doesn't contain them, though. I am talking about this PR.
The team is pretty busy though right now, adding new devices will take a long time. If you plan to maintain the devices, you may be able to join the team and push your trees to msm8916 git. Vince will be able to tell more.

**Comment by zqm64** [comment]
> The PR still doesn't contain them, though. I am talking about this PR.
> The team is pretty busy though right now, adding new devices will take a long time. If you plan to maintain the devices, you may be able to join the team and push your trees to msm8916 git. Vince will be able to tell more.

I would love to.
But I afraid If i made some changes that doesn't comply with proper rules(styles, and etc.), then makes them unhappy
As I have almost "0" programming experiences before.
Also my english is bad, don't know how to write commit messages properly

**Comment by zqm64** [comment]
One more question. Can I publish roms to XDA instead of waiting Vincent to do this?

**Comment by zakaryan2004** [comment]
XDA is open to everyone, you can publish whatever you want on your own there.

**Comment by zqm64** [comment]
Ok. I will upload my commits to gerrit and upload my own device trees to my github account soon.

**Pull request closed without merging**
